# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42eb9c6ae5aeb49e553d7ddaf2e3f6759038676ab5b7a223c58618a297c925b015e4ce35d1b1d47ba299a5337afae6f99a7e6d07c788c76ac3e631c07be569f7

test:
  secret_key_base: 7e1edee5ca885cafeeac9fc66e40816f27f0d357f5140885d3b84f9392e8f0320cfd2fb0e82aa9f9090204b2b3dcf67b52464c8016e233b8205608446785ffca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
